### ISSUE TITLE
Use controller to select a Node

### ISSUE THREAD

**Issue by Dorianux** [eu81273/angular.treeview#17]
How can i use a controller to select a Node (instead of clicking to select)?

I tried to set currentNode and hoped that it will trigger $scope.$watch,
but it does not.

**Comment by Dorianux** [comment]
To correct myself: 
Setting tagtree.currentNode does trigger $scope.$watch('tagtree.currentNode', ....,
still the visual selection is not updated in the view.

**Comment by Dorianux** [comment]
Found it: simply set: selected=True on the currentNode!

**Comment by schitupolu** [comment]
Hi,

I am also trying to pre-select. Can you please let me know where you added selected=True? When i try adding it on the currentNode doesn't highlight it in the html.
