### ISSUE TITLE
Any examples how to interactively add new nodes?

### ISSUE THREAD

**Issue by dparizek** [eu81273/angular.treeview#6]
I'm a total newb to Angular... any one have an example of how you would say have a button that when you click it you can add say a new child node to the currently selected node?

**Comment by eu81273** [comment]
I just made a quick example. It shows how edit/add node dynamically.

http://jsfiddle.net/eu81273/vL4TJ/

**Comment by dparizek** [comment]
THANKS!!!  You are fantastic!
